Vagrant.configure("2") do |config|
    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.define "dev", primary: true do |dev|
        dev.vm.network "private_network", ip: "33.33.33.110"

        dev.vm.synced_folder "./../www", "/var/www/current", nfs: true

        config.vm.provision :shell, :inline => 'if [[ ! -f /apt-get-run ]];
            then sudo apt-get update && sudo touch /apt-get-run; fi;'

        dev.vm.provision "puppet" do |puppet|
            puppet.facter = {
                "vm_env"            => "dev",
                "vm_host"           => "dev.roman.com",
                "vm_mysql_db"       => 'symfony',
                "vm_mysql_user"     => 'root',
                "vm_mysql_pass"     => '',
            }
            puppet.module_path = "modules"
            puppet.manifests_path = "manifests"
            # puppet.options = ['--verbose --debug']
        end
    end
end
